{{- if .Values.artifactRepository.secret.enabled -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.artifactRepository.secret.name }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "kubeaiops.labels" . | nindent 4 }}
type: Opaque
data:
  {{ .Values.artifactRepository.secret.accesskey.name }}: {{ .Values.artifactRepository.secret.accesskey.key | b64enc | quote }}
  {{ .Values.artifactRepository.secret.secretkey.name }}: {{ .Values.artifactRepository.secret.secretkey.key | b64enc | quote }}
{{- end }}  