apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "kubeaiops.fullname" . }}-cr
  labels:
        {{- include "kubeaiops.labels" . | nindent 4 }}
rules:
- apiGroups:
  - "*"
  resources:
  - "*"
  verbs:
  - "*"