apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "kubeaiops.fullname" . }}-crb
subjects:
  - kind: ServiceAccount
    name: {{ include "kubeaiops.serviceAccountName" . }}
    namespace: {{ .Release.Namespace }}      
roleRef:
  kind: ClusterRole
  name: {{ include "kubeaiops.fullname" . }}-cr
  apiGroup: rbac.authorization.k8s.io