apiVersion: aiops.kubeaiops.com/v1alpha1
kind: KubeMonitor
metadata:
  labels:
    {{- include "kubeaiops.labels" . | nindent 4 }}
  name: {{ include "kubeaiops.fullname" . }}-basicmonitor
  namespace: {{ .Release.Namespace }}
spec:
  # TODO(user): Add fields here
  cron: "* * * * *"
  maxWorkflowCount: {{ .Values.maxWorkflowCount }}
  arguments:
    parameters:
      - name: message
        value: "Hello Argo 11"
  workflow:
    namespace: {{ .Release.Namespace }}
    source: |-
      apiVersion: argoproj.io/v1alpha1
      kind: Workflow                  # new type of k8s spec
      metadata:
        generateName: hello-world-    # name of the workflow spec
        annotations:
          workflows.argoproj.io/controller-instanceid: kubemonitor
      spec:
        serviceAccountName:  {{ include "kubeaiops.serviceAccountName" . }}
        archive: false
        volumes:
          - name: my-volume
            emptyDir: {}
        arguments:
          parameters:
            - name: message
              value: 'Hello Argo'
        entrypoint: whalesay          # invoke the whalesay template
        templates:
          - name: whalesay              # name of the template
            inputs:
              parameters:
                - name: message
                  value: {{`'{{ workflow.parameters.message}}'`}}
            container:
              image: docker/whalesay
              command: [cowsay]
              args:
                - {{`'{{ inputs.parameters.message}}'`}}
              resources:                # limit the resources
                limits:
                  memory: 32Mi
                  cpu: 100m
              volumeMounts:
                - name: my-volume
                  mountPath: /my-data