{{- if .Values.minio.enabled -}}
apiVersion: v1
kind: Secret
metadata:
  name: my-minio-secret
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "kubeaiops.labels" . | nindent 4 }}
type: Opaque
data:
  accessKey: {{ .Values.minio.accessKey | b64enc | quote }}
  secretKey: {{ .Values.minio.secretKey | b64enc | quote }}
{{- end }}  