apiVersion: v1
kind: Service
metadata:
  name: {{ include "kubeaiops.fullname" . }}
  namespace: {{ .Release.Namespace }}  
  labels:
    {{- include "kubeaiops.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
    - port: 8080
      targetPort: http
      protocol: TCP
      name: metric
  selector:
    {{- include "kubeaiops.selectorLabels" . | nindent 4 }}
