apiVersion: aiops.kubeaiops.com/v1alpha1
kind: KubeMonitor
metadata:
  labels:
    app.kubernetes.io/name: kubemonitor
    app.kubernetes.io/instance: kubemonitor-sample
    app.kubernetes.io/part-of: kubeaiops
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/created-by: kubeaiops
  name: kubemonitor-sample
  namespace: kubemonitor
spec:
  # TODO(user): Add fields here
  cron: "* * * * *"
  workflow:
    name: test
    namespace: kubemonitor
    source: |-
      apiVersion: argoproj.io/v1alpha1
      kind: Workflow                  # new type of k8s spec
      metadata:
        generateName: hello-world-    # name of the workflow spec
      spec:
        entrypoint: whalesay          # invoke the whalesay template
        templates:
          - name: whalesay              # name of the template
            container:
              image: docker/whalesay
              command: [cowsay]
              args: ["hello world"]
              resources:                # limit the resources
                limits:
                  memory: 32Mi
                  cpu: 100m