---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: workflow-controller
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "argo.labels" . | nindent 4 }}  
spec:
  selector:
    matchLabels:
      {{- include "argo.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "argo.selectorLabels" . | nindent 8 }}
    spec:
      containers:
        - args: []
          command:
            - workflow-controller
          env:
            - name: LEADER_ELECTION_IDENTITY
              valueFrom:
                fieldRef:
                  apiVersion: v1
                  fieldPath: metadata.name
          image: argoproj/workflow-controller:v3.4.4
          livenessProbe:
            failureThreshold: 3
            httpGet:
              path: /healthz
              port: 6060
            initialDelaySeconds: 90
            periodSeconds: 60
            timeoutSeconds: 30
          name: workflow-controller
          ports:
            - containerPort: 9090
              name: metrics
            - containerPort: 6060
          securityContext:
            capabilities:
              drop:
                - ALL
      nodeSelector:
        kubernetes.io/os: linux
      securityContext:
        runAsNonRoot: true
      serviceAccountName: {{ .Values.serviceAccount.name }}
