apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: argo-role
  namespace: {{ .Release.Namespace }}
rules:
  - apiGroups:
      - "*"
    resources:
      - "*"
    verbs:
      - "*"