---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "argo.fullname" . }}
  namespace: {{ .Release.Namespace }}
spec:
  ports:
    - name: metrics
      port: 9090
      protocol: TCP
      targetPort: 9090
  selector:
    {{- include "argo.selectorLabels" . | nindent 4 }}